# Generated by Django 5.2.3 on 2025-06-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
