# Generated by Django 5.2.3 on 2025-06-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
    ]
